- name: configure payment server
  hosts: payment
  become: yes
  tasks:

  - name: install python
    ansible.builtin.dnf:
      name:
        - python3
        - gcc
        - python3-devel
      state: present

  - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download payment
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: unzip payment
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.pip:
      requirements: /app/requirements.txt
      executable: pip3

  - name: copy payment service
    ansible.builtin.template:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: reload systemd
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: start payment
    ansible.builtin.systemd:
      name: payment
      state: started
      enabled: yes